import Head from 'next/head'
import Header from '../components/Header'
import ShowsCollection from "../components/ShowsCollection";
import MoviesCollection from "../components/MoviesCollection";
import Footer from '../components/Footer';


export default function Home({
  popularMovies,
  popularShows,
  top_ratedMovies,
  top_ratedShows,
}) {

  return (
    <body style={{
        'background-image':
          'linear-gradient(rgb(1 180 228 / 30%), rgb(1 180 228 / 30%)), url(../img/bg2.jpg)',
      }}>
      <Head>
        <title>TMDB Clone Brilian</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="https://www.google.com/s2/u/0/favicons?domain=https://www.themoviedb.org/" />
      </Head>

      <Header />
      <main className="flex flex-col item-center justify-center md:px-12">
        <h1 className="font-bold text-5xl mt-14 text-white ">
          Welcome.
        </h1>
        <h2 className="font-bold text-3xl text-white mb-8">
          Millions of movies, TV shows and people to discover. Explore now.
        </h2>
        <div className="flex mt-4 mb-20 justify-center">
          <input
            placeholder="Search for a movie, tv show, person......."
            className="bg-white p-4 w-[1300px] rounded-l-full min-w-[400px] text-black"
          />
          <button
            className="flex items-center rounded-r-full bg-gradient-to-r from-cyan-500 to-blue-500 text-white text-xl px-8"
          >
            Search
          </button>
        </div>
      </main>
      <div className='pb-10' style={{
        'background-image':
          'url(../img/scattered-forcefields.svg)',
        }}>
        <MoviesCollection results={popularMovies} title="Popular Movies" />
        <ShowsCollection results={popularShows} title="Popular Shows" />
        <MoviesCollection results={top_ratedMovies} title="Top Rated Movies" />
        <ShowsCollection results={top_ratedShows} title="Top Rated Shows" />
      </div>

      <Footer />
    </body>
  )
}

export async function getServerSideProps(context) {

  const [
    popularMoviesRes,
    popularShowsRes,
    top_ratedMoviesRes,
    top_ratedShowsRes,
  ] = await Promise.all([
    fetch(
      `https://api.themoviedb.org/3/movie/popular?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ),
    fetch(
      `https://api.themoviedb.org/3/tv/popular?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ),
    fetch(
      `https://api.themoviedb.org/3/movie/top_rated?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ),
    fetch(
      `https://api.themoviedb.org/3/tv/top_rated?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ),
  ]);
  const [popularMovies, popularShows, top_ratedMovies, top_ratedShows] =
    await Promise.all([
      popularMoviesRes.json(),
      popularShowsRes.json(),
      top_ratedMoviesRes.json(),
      top_ratedShowsRes.json(),
    ]);

  return {
    props: {
      popularMovies: popularMovies.results,
      popularShows: popularShows.results,
      top_ratedMovies: top_ratedMovies.results,
      top_ratedShows: top_ratedShows.results,
    },
  };
}